import { Dimensions } from "react-native";
export const Screen = {
  width: Dimensions.get("window").width,
  height: Dimensions.get("window").height,
};
export const TodoList = [
  {
    id: 1,
    name: "Laundry",
    description: "Short description of what needs to be done",
    targetCompletion: "2020-05-29",
    actualCompletion: "",
    completed: false,
    color: "#f47373",
  },
  {
    id: 2,
    name: "Wash Car",
    description: "Short description of what needs to be done",
    targetCompletion: "2020-05-29",
    actualCompletion: "",
    completed: false,
    color: "#697689",
  },
  {
    id: 3,
    name: "Update Windows",
    description: "Short description of what needs to be done",
    targetCompletion: "2020-05-29",
    actualCompletion: "",
    completed: false,
    color: "#37d67a",
  },
  {
    id: 4,
    name: "Walk Dogs",
    description: "Short description of what needs to be done",
    targetCompletion: "2020-05-29",
    actualCompletion: "",
    completed: false,
    color: "#ba68c8",
  },
  {
    id: 5,
    name: "Walk Dogs",
    description: "Short description of what needs to be done", 
    targetCompletion: "2020-05-29",
    actualCompletion: "",
    completed: false,
    color: "#ff8a65",
  },
];

export const Colors = [
  { color: "#D9E3F0" },
  { color: "#F47373" },
  { color: "#697689" },
  { color: "#37D67A" },
  { color: "#2CCCE4" },
  { color: "#555555" },
  { color: "#dce775" },
  { color: "#ff8a65" },
  { color: "#ba68c8" },
  { color: "#4caf50" },
  { color: "#8ed1fc" },
  { color: "#7bdcb5" },
  { color: "#00BCD4" },
  { color: "#ffc107" },
  { color: "#e57373" },
  { color: "##bedadc" },
  { color: "#795548" },
  { color: "#607d8b" },
];
